name: Deploy Docker Image

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: [self-hosted, linux]

        steps:
            - uses: actions/checkout@v3

            - name: Build the Docker image
              run: docker build --file Dockerfile -t ffa-website:latest -t ffa-website:$(date +%s) .
              
            - name: Remove existing containers
              run: docker rm -f ffa-website

            - name: Deploy
              run: docker run -d \
                  --name ffa-website \
                  -p 127.0.0.1:8080:8080 \
                  -e NUXT_ANTBOX_URL="https://pvt2.kindalus.me" \
                  -e NUXT_PUBLIC_ANTBOX_URL="https://pvt2.kindalus.me" \
                  --restart unless-stopped \
                  ffa-website:latest
